version: '3.8'

services:
  reviews-microservice:
    build: ./reviews-microservice
    ports:
      - "8001:8000"  
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_USER=aitor
      - DB_PASSWORD=root
      - DB_NAME=bookreviewhub
    depends_on:
      - db

  auth-microservice:
    build: ./express-auth-api
    ports:
      - "8002:3000"  
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_USER=aitor
      - DB_PASSWORD=root
      - DB_NAME=bookreviewhub
    depends_on:
      - db

  main-app:
    build: ./fastapi-gateway
    ports:
      - "8080:8000"  
    networks:
      - app-network
    environment:
      - REVIEW_SERVICE_URL=http://reviews-microservice:8000
      - AUTH_SERVICE_URL=http://auth-microservice:3000/api/user
    depends_on:
      - reviews-microservice
      - auth-microservice

  db:
    image: mysql:8.0
    container_name: bookreviewhub_db
    ports:
      - "3307:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookreviewhub
    volumes:
      - db_data:/var/lib/mysql
      - ./database-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
