openapi: 3.0.0
info:
  title: User Authentication API
  version: 1.0.0
paths:
  /api/user/register:
    post:
      summary: Registrar un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Usuario registrado exitosamente
        '400':
          description: El usuario ya existe
        '500':
          description: Error interno del servidor
  /api/user/login:
    post:
      summary: Iniciar sesión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Credenciales inválidas
        '500':
          description: Error interno del servidor
